blank_issues_enabled: false
contact_links:
  - name: submit a bug
    about: 🗨 Start a friendly conversation with the other members of the community about the samples in this repository.
    url: https://github.com/wenjingjiang/example_repo/blob/wenjingjiang-patch-1/.github/ISSUE_TEMPLATE/bug_report.yml
  - name: Microsoft Tech Community
    url: https://techcommunity.microsoft.com/t5/power-platform/bd-p/PowerPlatform
    about: ⁉️ Alternatively, submit your technical questions in the Power Platform Tech Community
